### ISSUE TITLE
Is there any follow up to this project?

### ISSUE THREAD

**Issue by kovacsgergely83** [MAVProxyUser/dji.nfzdb#2]
Hi MavProxyUser,

I'm building up a Google Earth Pro / Google MyMaps based project called "The SmithDroneian Hungraian BucketList v2.0" for drone photographers and cinematographers of spots in Hungary that worth a shot/footage.

PROD KML: https://drive.google.com/file/d/1-fTe8Jc28owssMqm55hxbxD4iIy6Vpoz/view?usp=sharing
PROD MyMaps: https://drive.google.com/open?id=1AmM4m57_Ev6szV0VqhJZYdL_8xcYj1bq&usp=sharing
CONTRIBUTE MyMaps: https://drive.google.com/open?id=1jHsj49BMILLEWmsPTYLO8s5aJdhFxate&usp=sharing

For that I'm already in the process of extracting the DJI SafeFly DB (https://www.dji.com/flysafe/geo-map#active) from the JSON: https://www-api.dji.com/hu/api/geo/areas?lng=19.05835771093758&lat=47.177431579954565&country=HU&search_radius=247882&drone=spark&level=1%2C2%2C4%2C7&zones_mode=total, so that I can layer the NFZ info upon the map, but a bit stuck on how to convert it to CSV / KML, especially for the non-circle shaped new GEO2.0 airport zones, if you know what I mean (https://www.dji.com/flysafe/introduction)

In the meantime I've found your amazing project and understood that you have extracted your NFZ CSV / KML from the DJI Go app itself, from its MySQL. Can you describe the steps, how to get from the MySQL data to the KML file itself?

Many thanks,
Gergely "The SmithDroneian" Smith

**Comment by MAVProxyUser** [comment]
Sorry brother, I have retired from the drone scene. Please seek out the "Slack OGs". You can find the link to join slack here in the "Alternative CopterSafe Hack & Mod Discussion" thread on Hak5 

https://forums.hak5.org/topic/41304-mavicpilotscom-alternative-coptersafe-hack-mod-discussion/

If you are lazy this is the slack join link https://join.slack.com/t/dji-rev/shared_invite/enQtMjk5OTEyMzcyMjI3LTdlZjY4NzQ5M2M2NmE5ZWM4OTgyNThmZDVmZjdjODE4ODYyNmYwZjYxMDcyYzcxNmZlYzI5ZjI2ZGQ2NGY1ZTc

**Comment by kovacsgergely83** [comment]
Many thanks for the swift reply and further hints, take care, brother. ;)
